  profiles:
    active:
    - dev
---
server:
  port: 6666
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://192.168.250.111:9502/eureka/
---
server:
  port: 6666
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9502/eureka/